#include "audio_engine.h"
#include "audio_hal.h"
#include "wakeword.h"
#include "esp_aec.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "esp_err.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/semphr.h"
#include <string.h>

namespace {
static const char *TAG="AUDIO_ENGINE";
static constexpr size_t PCM_BLOCK_SAMPLES=512,MIC_FRAME_SAMPLES=320,MIC_FRAME_BYTES=640,MIC_QUEUE_DEPTH=250,PLAYBACK_BLOCK_SAMPLES=1024,PLAYBACK_BLOCK_BYTES=2048,PLAYBACK_QUEUE_DEPTH=94,AEC_FRAME_SAMPLES=512,AEC_REF_RING_SAMPLES=32768,AEC_REF_DELAY_SAMPLES=1280;
static constexpr uint32_t WAKEWORD_TASK_STACK=8192,CONVERSATION_TASK_STACK=4096,PLAYBACK_TASK_STACK=4096;
static constexpr TickType_t BUFFER_WAIT_TICKS=pdMS_TO_TICKS(20);
struct PlaybackBlock{uint16_t samples;int16_t pcm[PLAYBACK_BLOCK_SAMPLES];};
static int16_t s_pcm_buffer[PCM_BLOCK_SAMPLES];
static TaskHandle_t s_wakeword_task=nullptr,s_conversation_task=nullptr,s_playback_task=nullptr;
static bool s_initialized=false;
static volatile bool s_wakeword_running=false,s_wakeword_detected=false,s_conversation_running=false,s_playback_running=false,s_playback_processing=false;
static StaticQueue_t s_mic_free_storage,s_mic_ready_storage,s_playback_free_storage,s_playback_ready_storage;
static uint8_t *s_mic_free_buffer[MIC_QUEUE_DEPTH],*s_mic_ready_buffer[MIC_QUEUE_DEPTH],*s_mic_buffers[MIC_QUEUE_DEPTH]={};
static PlaybackBlock *s_playback_free_buffer[PLAYBACK_QUEUE_DEPTH],*s_playback_ready_buffer[PLAYBACK_QUEUE_DEPTH],*s_playback_buffers[PLAYBACK_QUEUE_DEPTH]={};
static QueueHandle_t s_mic_free_queue=nullptr,s_mic_ready_queue=nullptr,s_playback_free_queue=nullptr,s_playback_ready_queue=nullptr;

static aec_handle_t *s_aec=nullptr;static int16_t *s_aec_mic=nullptr,*s_aec_ref=nullptr,*s_aec_out=nullptr,*s_aec_ref_ring=nullptr;
static size_t s_ref_head=0,s_ref_tail=0,s_ref_count=0;static portMUX_TYPE s_ref_mux=portMUX_INITIALIZER_UNLOCKED;
static bool s_ref_have_prev=false;static int16_t s_ref_prev=0;static int s_ref_phase_half=0;

static void free_audio_pools(){for(size_t i=0;i<MIC_QUEUE_DEPTH;i++)if(s_mic_buffers[i]){heap_caps_free(s_mic_buffers[i]);s_mic_buffers[i]=nullptr;}for(size_t i=0;i<PLAYBACK_QUEUE_DEPTH;i++)if(s_playback_buffers[i]){heap_caps_free(s_playback_buffers[i]);s_playback_buffers[i]=nullptr;}}
static bool init_audio_pools(){
 s_mic_free_queue=xQueueCreateStatic(MIC_QUEUE_DEPTH,sizeof(uint8_t*),reinterpret_cast<uint8_t*>(s_mic_free_buffer),&s_mic_free_storage);s_mic_ready_queue=xQueueCreateStatic(MIC_QUEUE_DEPTH,sizeof(uint8_t*),reinterpret_cast<uint8_t*>(s_mic_ready_buffer),&s_mic_ready_storage);s_playback_free_queue=xQueueCreateStatic(PLAYBACK_QUEUE_DEPTH,sizeof(PlaybackBlock*),reinterpret_cast<uint8_t*>(s_playback_free_buffer),&s_playback_free_storage);s_playback_ready_queue=xQueueCreateStatic(PLAYBACK_QUEUE_DEPTH,sizeof(PlaybackBlock*),reinterpret_cast<uint8_t*>(s_playback_ready_buffer),&s_playback_ready_storage);if(!s_mic_free_queue||!s_mic_ready_queue||!s_playback_free_queue||!s_playback_ready_queue)return false;
 for(size_t i=0;i<MIC_QUEUE_DEPTH;i++){s_mic_buffers[i]=(uint8_t*)heap_caps_malloc(MIC_FRAME_BYTES,MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);if(!s_mic_buffers[i]||xQueueSend(s_mic_free_queue,&s_mic_buffers[i],0)!=pdPASS){free_audio_pools();return false;}}
 for(size_t i=0;i<PLAYBACK_QUEUE_DEPTH;i++){s_playback_buffers[i]=(PlaybackBlock*)heap_caps_malloc(PLAYBACK_BLOCK_BYTES+sizeof(uint16_t),MALLOC_CAP_SPIRAM|MALLOC_CAP_8BIT);if(!s_playback_buffers[i]||xQueueSend(s_playback_free_queue,&s_playback_buffers[i],0)!=pdPASS){free_audio_pools();return false;}s_playback_buffers[i]->samples=0;}return true;}

static bool init_aec(){aec_config_t c={};c.mic_num=1;c.ref_num=1;c.out_num=1;c.filter_length=4;c.sample_rate=16000;c.caps=MALLOC_CAP_PSRAM|MALLOC_CAP_8BIT;c.mode=AEC_MODE_FD_LOW_COST;c.nlp_level=AEC_NLP_LEVEL_NORMAL;s_aec=aec_create_from_config(&c);if(!s_aec){ESP_LOGE(TAG,"AEC init gagal");return false;}if(aec_get_chunksize(s_aec)!=(int)AEC_FRAME_SAMPLES){ESP_LOGE(TAG,"AEC chunk tidak 512");aec_destroy(s_aec);s_aec=nullptr;return false;}s_aec_mic=(int16_t*)heap_caps_aligned_alloc(16,AEC_FRAME_SAMPLES*2,MALLOC_CAP_PSRAM|MALLOC_CAP_8BIT);s_aec_ref=(int16_t*)heap_caps_aligned_alloc(16,AEC_FRAME_SAMPLES*2,MALLOC_CAP_PSRAM|MALLOC_CAP_8BIT);s_aec_out=(int16_t*)heap_caps_aligned_alloc(16,AEC_FRAME_SAMPLES*2,MALLOC_CAP_PSRAM|MALLOC_CAP_8BIT);s_aec_ref_ring=(int16_t*)heap_caps_malloc(AEC_REF_RING_SAMPLES*2,MALLOC_CAP_PSRAM|MALLOC_CAP_8BIT);if(!s_aec_mic||!s_aec_ref||!s_aec_out||!s_aec_ref_ring){ESP_LOGE(TAG,"AEC buffer allocation gagal");return false;}return true;}
static void reset_ref(){portENTER_CRITICAL(&s_ref_mux);s_ref_head=s_ref_tail=s_ref_count=0;portEXIT_CRITICAL(&s_ref_mux);s_ref_have_prev=false;s_ref_prev=0;s_ref_phase_half=0;}
static void push_ref(int16_t v){portENTER_CRITICAL(&s_ref_mux);if(s_ref_count>=AEC_REF_RING_SAMPLES){s_ref_tail=(s_ref_tail+1)%AEC_REF_RING_SAMPLES;--s_ref_count;}s_aec_ref_ring[s_ref_head]=v;s_ref_head=(s_ref_head+1)%AEC_REF_RING_SAMPLES;++s_ref_count;portEXIT_CRITICAL(&s_ref_mux);}
static void push_ref_24k(const int16_t *p,size_t n){if(!p||!n)return;for(size_t i=0;i<n;i++){int16_t x=p[i];if(!s_ref_have_prev){s_ref_prev=x;s_ref_have_prev=true;s_ref_phase_half=3;push_ref(x);continue;}while(s_ref_phase_half<=2){int16_t y=s_ref_prev;if(s_ref_phase_half==1)y=(int16_t)(((int32_t)s_ref_prev+(int32_t)x)/2);else if(s_ref_phase_half==2)y=x;push_ref(y);s_ref_phase_half+=3;}s_ref_prev=x;s_ref_phase_half-=2;}}
static void pop_ref(int16_t *p){portENTER_CRITICAL(&s_ref_mux);for(size_t i=0;i<AEC_FRAME_SAMPLES;i++){if(s_ref_count>AEC_REF_DELAY_SAMPLES){p[i]=s_aec_ref_ring[s_ref_tail];s_ref_tail=(s_ref_tail+1)%AEC_REF_RING_SAMPLES;--s_ref_count;}else p[i]=0;}portEXIT_CRITICAL(&s_ref_mux);}

static void wakeword_task(void*){while(s_wakeword_running){if(audio_engine_process_wakeword())ESP_LOGI(TAG,"WakeWord terdeteksi");vTaskDelay(pdMS_TO_TICKS(1));}s_wakeword_task=nullptr;vTaskDelete(nullptr);}
static void queue_mic(const int16_t *p){uint8_t *f=nullptr;while(s_conversation_running&&xQueueReceive(s_mic_free_queue,&f,BUFFER_WAIT_TICKS)!=pdTRUE){}if(!s_conversation_running||!f)return;memcpy(f,p,MIC_FRAME_BYTES);while(s_conversation_running&&xQueueSend(s_mic_ready_queue,&f,BUFFER_WAIT_TICKS)!=pdTRUE){}if(!s_conversation_running)(void)xQueueSend(s_mic_free_queue,&f,0);}
static void conversation_task(void*){static int16_t raw[AEC_FRAME_SAMPLES],frame[AEC_FRAME_SAMPLES];size_t pos=0;while(s_conversation_running){size_t n=0;esp_err_t e=audio_hal_read_pcm(raw,AEC_FRAME_SAMPLES,&n);if(e!=ESP_OK||!n){if(s_conversation_running)vTaskDelay(pdMS_TO_TICKS(1));continue;}memcpy(s_aec_mic,raw,n*2);if(n<AEC_FRAME_SAMPLES)memset(s_aec_mic+n,0,(AEC_FRAME_SAMPLES-n)*2);pop_ref(s_aec_ref);aec_process(s_aec,s_aec_mic,s_aec_ref,s_aec_out);for(size_t i=0;i<AEC_FRAME_SAMPLES&&s_conversation_running;i++){frame[pos++]=s_aec_out[i];if(pos==MIC_FRAME_SAMPLES){queue_mic(frame);pos=0;}}}s_conversation_task=nullptr;vTaskDelete(nullptr);}
static void playback_task(void*){PlaybackBlock *b=nullptr;while(s_playback_running){if(xQueueReceive(s_playback_ready_queue,&b,pdMS_TO_TICKS(20))!=pdTRUE)continue;if(!b)continue;s_playback_processing=true;size_t off=0;while(s_playback_running&&off<b->samples){size_t written=0;esp_err_t e=audio_hal_write_pcm(b->pcm+off,b->samples-off,&written);if(written>b->samples-off)written=0;if(written)push_ref_24k(b->pcm+off,written);off+=written;if(off<b->samples&&(e!=ESP_OK||written==0))vTaskDelay(pdMS_TO_TICKS(5));}b->samples=0;(void)xQueueSend(s_playback_free_queue,&b,BUFFER_WAIT_TICKS);s_playback_processing=false;}s_playback_task=nullptr;vTaskDelete(nullptr);}
static bool stop_wakeword_and_wait(){if(!s_wakeword_running&&s_wakeword_task==nullptr)return true;s_wakeword_running=false;audio_hal_stop_capture();for(uint32_t i=0;i<100&&s_wakeword_task;i++)vTaskDelay(pdMS_TO_TICKS(1));return s_wakeword_task==nullptr;}
}

extern "C" bool audio_engine_init(void){if(s_initialized)return true;audio_hal_init();if(!wakeword_init())return false;if(wakeword_get_sample_rate()!=16000){wakeword_deinit();return false;}if(!init_audio_pools()){wakeword_deinit();return false;}if(!init_aec()){wakeword_deinit();free_audio_pools();return false;}s_wakeword_detected=false;s_wakeword_running=false;s_conversation_running=false;s_playback_running=false;s_initialized=true;ESP_LOGI(TAG,"AEC aktif: FD_LOW_COST 16k, reference 24k->16k, delay=80ms");return true;}
extern "C" bool audio_engine_start_wakeword(void){if(!s_initialized||s_wakeword_running||s_conversation_running)return !s_conversation_running;s_wakeword_detected=false;if(audio_hal_start_capture()!=ESP_OK)return false;s_wakeword_running=true;if(xTaskCreate(wakeword_task,"wakeword_task",WAKEWORD_TASK_STACK,nullptr,6,&s_wakeword_task)!=pdPASS){s_wakeword_running=false;audio_hal_stop_capture();return false;}return true;}
extern "C" void audio_engine_stop_wakeword(void){s_wakeword_running=false;audio_hal_stop_capture();}
extern "C" bool audio_engine_process_wakeword(void){if(!s_initialized||!s_wakeword_running)return false;size_t n=0;if(audio_hal_read_pcm(s_pcm_buffer,PCM_BLOCK_SAMPLES,&n)!=ESP_OK||!n)return false;if(wakeword_process_pcm16(s_pcm_buffer,n)){s_wakeword_detected=true;return true;}return false;}
extern "C" bool audio_engine_wakeword_detected(void){return s_wakeword_detected;}
extern "C" void audio_engine_clear_wakeword(void){s_wakeword_detected=false;}
extern "C" void audio_engine_stop(void){audio_engine_stop_wakeword();audio_engine_stop_conversation();audio_engine_stop_playback();}
extern "C" bool audio_engine_start_conversation(void){if(!s_initialized||s_conversation_running)return s_conversation_running;if(!stop_wakeword_and_wait())return false;if(audio_hal_start_capture()!=ESP_OK)return false;xQueueReset(s_mic_free_queue);xQueueReset(s_mic_ready_queue);for(size_t i=0;i<MIC_QUEUE_DEPTH;i++)(void)xQueueSend(s_mic_free_queue,&s_mic_buffers[i],0);reset_ref();s_conversation_running=true;if(xTaskCreate(conversation_task,"audio_conversation",CONVERSATION_TASK_STACK,nullptr,5,&s_conversation_task)!=pdPASS){s_conversation_running=false;audio_hal_stop_capture();s_conversation_task=nullptr;return false;}return true;}
extern "C" void audio_engine_stop_conversation(void){if(!s_conversation_running&&s_conversation_task==nullptr)return;s_conversation_running=false;audio_hal_stop_capture();for(uint32_t i=0;i<200&&s_conversation_task;i++)vTaskDelay(pdMS_TO_TICKS(1));xQueueReset(s_mic_ready_queue);xQueueReset(s_mic_free_queue);for(size_t i=0;i<MIC_QUEUE_DEPTH;i++)(void)xQueueSend(s_mic_free_queue,&s_mic_buffers[i],0);}
extern "C" bool audio_engine_conversation_active(void){return s_conversation_running;}
extern "C" bool audio_engine_read_mic_frame(int16_t *buffer,size_t samples,uint32_t timeout_ms){if(!buffer||samples!=MIC_FRAME_SAMPLES||!s_mic_ready_queue)return false;TickType_t wait=timeout_ms==UINT32_MAX?portMAX_DELAY:pdMS_TO_TICKS(timeout_ms);uint8_t *f=nullptr;if(xQueueReceive(s_mic_ready_queue,&f,wait)!=pdTRUE||!f)return false;memcpy(buffer,f,MIC_FRAME_BYTES);while(xQueueSend(s_mic_free_queue,&f,BUFFER_WAIT_TICKS)!=pdTRUE){if(!s_conversation_running)break;}return true;}
extern "C" size_t audio_engine_mic_frame_samples(void){return MIC_FRAME_SAMPLES;}
extern "C" bool audio_engine_start_playback(void){if(!s_initialized)return false;if(s_playback_running)return true;if(audio_hal_start_playback()!=ESP_OK)return false;xQueueReset(s_playback_free_queue);xQueueReset(s_playback_ready_queue);for(size_t i=0;i<PLAYBACK_QUEUE_DEPTH;i++){s_playback_buffers[i]->samples=0;(void)xQueueSend(s_playback_free_queue,&s_playback_buffers[i],0);}s_playback_running=true;s_playback_processing=false;s_ref_have_prev=false;s_ref_prev=0;s_ref_phase_half=0;if(xTaskCreate(playback_task,"audio_playback",PLAYBACK_TASK_STACK,nullptr,5,&s_playback_task)!=pdPASS){s_playback_running=false;audio_hal_stop_playback();s_playback_task=nullptr;return false;}return true;}
extern "C" void audio_engine_stop_playback(void){if(!s_playback_running&&s_playback_task==nullptr)return;s_playback_running=false;xQueueReset(s_playback_ready_queue);for(uint32_t i=0;i<200&&s_playback_task;i++)vTaskDelay(pdMS_TO_TICKS(1));xQueueReset(s_playback_free_queue);for(size_t i=0;i<PLAYBACK_QUEUE_DEPTH;i++){s_playback_buffers[i]->samples=0;(void)xQueueSend(s_playback_free_queue,&s_playback_buffers[i],0);}audio_hal_stop_playback();}
extern "C" bool audio_engine_playback_active(void){return s_playback_running;}
extern "C" bool audio_engine_drain_playback(void){if(!s_playback_task)return true;const int64_t deadline=esp_timer_get_time()+15000000LL;while(esp_timer_get_time()<deadline){if(uxQueueMessagesWaiting(s_playback_ready_queue)==0&&!s_playback_processing)break;vTaskDelay(pdMS_TO_TICKS(20));}if(uxQueueMessagesWaiting(s_playback_ready_queue)!=0||s_playback_processing){ESP_LOGE(TAG,"Speaker drain timeout: ready=%u processing=%d",(unsigned)uxQueueMessagesWaiting(s_playback_ready_queue),(int)s_playback_processing);return false;}s_playback_running=false;for(uint32_t i=0;i<200&&s_playback_task;i++)vTaskDelay(pdMS_TO_TICKS(1));xQueueReset(s_playback_free_queue);for(size_t i=0;i<PLAYBACK_QUEUE_DEPTH;i++){s_playback_buffers[i]->samples=0;(void)xQueueSend(s_playback_free_queue,&s_playback_buffers[i],0);}audio_hal_stop_playback();return true;}
extern "C" bool audio_engine_write_speaker_pcm(const int16_t *buffer,size_t samples,uint32_t timeout_ms){if(!buffer||!samples||!s_playback_running||!s_playback_free_queue)return false;TickType_t wait=timeout_ms==UINT32_MAX?portMAX_DELAY:pdMS_TO_TICKS(timeout_ms);size_t off=0;while(off<samples&&s_playback_running){PlaybackBlock *b=nullptr;while(xQueueReceive(s_playback_free_queue,&b,wait)!=pdTRUE){if(!s_playback_running)return false;}if(!b)return false;size_t n=(samples-off)>PLAYBACK_BLOCK_SAMPLES?PLAYBACK_BLOCK_SAMPLES:(samples-off);b->samples=(uint16_t)n;memcpy(b->pcm,buffer+off,n*2);while(s_playback_running&&xQueueSend(s_playback_ready_queue,&b,wait)!=pdTRUE){}if(!s_playback_running){b->samples=0;(void)xQueueSend(s_playback_free_queue,&b,0);return false;}off+=n;}return off==samples;}
